---

- name: "Start project containers: {{ project_name }}"
  ansible.builtin.command: "{{ docker_cli }} compose up --quiet-pull -d"
  args:
    chdir: "{{ project_path }}"
  register: up_result
  changed_when: up_result.stderr_lines | select('match', '.* Starting')
  ignore_errors: true

- name: "Show project start result: {{ project_name }}"
  ansible.builtin.debug:
    msg: "{{ up_result.stderr_lines }}"
  changed_when: up_result.changed
