---

- name: "Restart project containers: {{ docker_project_name }}"
  ansible.builtin.command: "{{ docker_cli }} compose restart"
  args:
    chdir: "{{ docker_project_path }}"
  register: restart_result
  ignore_errors: true
  changed_when: true

- name: "Show project restart result: {{ docker_project_name }}"
  ansible.builtin.debug:
    msg: "{{ restart_result.stderr_lines }}"
