---

- name: Reset Docker project vars
  ansible.builtin.set_fact:
    traefik_domains: []
    traefik_domain_label: ''
    traefik_subdomain_label: ''
    traefik_project_base_host_rules: ''
    traefik_project_base_labels: 'traefik.enable: false'
    docker_project_service_network_options: ''
    docker_project_default_network: ''
    docker_project_networks: ''

- name: Setup Docker project Traefik vars
  when: docker_project_traefik_enable
  ansible.builtin.include_tasks: _init_traefik_vars.yml

- name: Setup Docker project service network options
  when: docker_project_network_mode != 'bridge'
  ansible.builtin.set_fact:
    docker_project_service_network_options: "network_mode: {{ docker_project_network_mode }}"

- name: Setup Docker project networks
  when: docker_project_network_mode == 'bridge'
  vars:
    _docker_project_default_network: |-
      #jinja2: trim_blocks: True, lstrip_blocks: True
      default:
        driver: bridge
        ipam:
          driver: default
          {% if (docker_project_compose_ipv4_subnet | default(false)) or (docker_project_compose_ipv6_subnet | default(false)) %}
          config:
            {% if docker_project_compose_ipv4_subnet | default(false) %}
            - subnet: {{ docker_project_compose_ipv4_subnet | default('') }}
            {% endif %}
            {% if docker_project_compose_ipv6_subnet | default(false) %}
            - subnet: {{ docker_project_compose_ipv6_subnet | default('') }}
            {% endif %}
          {% endif %}
        {% if docker_project_compose_ipv6_subnet | default(false) %}
        enable_ipv6: true
        {% endif %}
  ansible.builtin.set_fact:
    docker_project_service_network_options: "{{
        (docker_project_additional_networks | length > 0) | ternary(
          'networks:\n' ~
          '  - default\n' ~
          '  - ' ~ docker_project_additional_networks | join('\n  - '), '')
      }}"
    docker_project_default_network: "{{ _docker_project_default_network }}"
    docker_project_networks: |-
      #jinja2: trim_blocks: True, lstrip_blocks: True
      networks:
        {{ _docker_project_default_network | indent(2) }}
        {% for item in docker_project_additional_networks %}
        {{ item }}:
          external: true
        {% endfor %}

- name: Debug Docker project vars
  when: not docker_project_traefik_enable
  ansible.builtin.debug:
    verbosity: 1
    msg:
      - "docker_project_name:   {{ docker_project_name }}"
      - "docker_project_slug:   {{ docker_project_slug }}"
      - "docker_project_prefix: {{ docker_project_prefix }}"
      - ""
      - "docker_project_path: {{ docker_project_path }}"
      - ""
      - "docker_project_traefik_enable ({{ docker_project_prefix }}_traefik_enable): {{ docker_project_traefik_enable }}"
      - ""
      - "docker_project_network_mode        ({{ docker_project_prefix }}_network_mode):        {{ docker_project_network_mode }}"
      - "docker_project_compose_ipv4_subnet ({{ docker_project_prefix }}_compose_ipv4_subnet): {{ docker_project_compose_ipv4_subnet }}"
      - "docker_project_compose_ipv6_subnet ({{ docker_project_prefix }}_compose_ipv6_subnet): {{ docker_project_compose_ipv6_subnet }}"
      - "docker_project_default_network:"
      - "{{ docker_project_default_network.split('\n') | reject('eq', '') }}"
      - "docker_project_additional_networks ({{ docker_project_prefix }}_additional_networks):"
      - "{{ docker_project_additional_networks }}"
      - ""
      - "docker_project_compose_additional_options         ({{ docker_project_prefix }}_compose_additional_options):"
      - "{{ docker_project_compose_additional_options.split('\n') | reject('eq', '') }}"
      - "docker_project_compose_service_additional_options ({{ docker_project_prefix }}_compose_service_additional_options):"
      - "{{ docker_project_compose_service_additional_options.split('\n') | reject('eq', '') }}"

- name: Debug Docker project vars
  when: docker_project_traefik_enable
  ansible.builtin.debug:
    verbosity: 1
    msg:
      - "docker_project_name:   {{ docker_project_name }}"
      - "docker_project_slug:   {{ docker_project_slug }}"
      - "docker_project_prefix: {{ docker_project_prefix }}"
      - ""
      - "docker_project_path: {{ docker_project_path }}"
      - ""
      - "docker_project_traefik_enable ({{ docker_project_prefix }}_traefik_enable): {{ docker_project_traefik_enable }}"
      - ""
      - "docker_project_traefik_"
      - "    _domain                     ({{ docker_project_prefix }}_traefik_domain):                     {{ docker_project_traefik_domain }}"
      - "    _subdomain                  ({{ docker_project_prefix }}_traefik_subdomain):                  {{ docker_project_traefik_subdomain }}"
      - "    _router_service             ({{ docker_project_prefix }}_traefik_router_service):             {{ docker_project_traefik_router_service }}"
      - "    _loadbalancer_server_port   ({{ docker_project_prefix }}_traefik_loadbalancer_server_port):   {{ docker_project_traefik_loadbalancer_server_port }}"
      - "    _loadbalancer_server_scheme ({{ docker_project_prefix }}_traefik_loadbalancer_server_scheme): {{ docker_project_traefik_loadbalancer_server_scheme }}"
      - "    _entrypoints                ({{ docker_project_prefix }}_traefik_entrypoints):                {{ docker_project_traefik_entrypoints }}"
      - "    _middlewares                ({{ docker_project_prefix }}_traefik_middlewares):                {{ docker_project_traefik_middlewares }}"
      - ""
      - "docker_project_traefik_define_internal_route  ({{ docker_project_prefix }}_traefik_define_internal_route): {{ docker_project_traefik_define_internal_route }}"
      - "docker_project_traefik_middlewares_internal   ({{ docker_project_prefix }}_traefik_middlewares_internal):  {{ docker_project_traefik_middlewares_internal }}"
      - ""
      - "docker_project_traefik_custom_labels  ({{ docker_project_prefix }}_traefik_custom_labels):"
      - "{{ docker_project_traefik_custom_labels.split('\n') | reject('eq', '') }}"
      - ""
      - "traefik_domain_label:            {{ traefik_domain_label }}"
      - "traefik_subdomain_label:         {{ traefik_subdomain_label }}"
      - "traefik_domains:                 {{ traefik_domains }}"
      - "traefik_project_base_host_rules: {{ traefik_project_base_host_rules }}"
      - ""
      - "traefik_project_base_labels:"
      - "{{ traefik_project_base_labels.split('\n') | reject('eq', '') }}"
      - ""
      - "docker_project_network_mode        ({{ docker_project_prefix }}_network_mode):        {{ docker_project_network_mode }}"
      - "docker_project_compose_ipv4_subnet ({{ docker_project_prefix }}_compose_ipv4_subnet): {{ docker_project_compose_ipv4_subnet }}"
      - "docker_project_compose_ipv6_subnet ({{ docker_project_prefix }}_compose_ipv6_subnet): {{ docker_project_compose_ipv6_subnet }}"
      - "docker_project_default_network:"
      - "{{ docker_project_default_network.split('\n') | reject('eq', '') }}"
      - "docker_project_additional_networks ({{ docker_project_prefix }}_additional_networks):"
      - "{{ docker_project_additional_networks }}"
      - ""
      - "docker_project_compose_additional_options         ({{ docker_project_prefix }}_compose_additional_options):"
      - "{{ docker_project_compose_additional_options.split('\n') | reject('eq', '') }}"
      - "docker_project_compose_service_additional_options ({{ docker_project_prefix }}_compose_service_additional_options):"
      - "{{ docker_project_compose_service_additional_options.split('\n') | reject('eq', '') }}"
