---

- name: Reset traefik variables
  ansible.builtin.set_fact:
    traefik_domain_label_value:
    traefik_subdomain_label_value:
    traefik_domains:
    traefik_project_base_host_rules:
    traefik_project_base_labels:
    traefik_project_default_network:


- name: Setup traefik snippets
  vars:
    _prefix: "{{ project_name | regex_replace('[^\\w]', '_') }}"

    _traefik_enable:                   "{{ lookup('vars', _prefix ~ '_traefik_enable',                   default=true) }}"
    _traefik_domain:                   "{{ lookup('vars', _prefix ~ '_traefik_domain',                   default='') }}"
    _traefik_subdomain:                "{{ lookup('vars', _prefix ~ '_traefik_subdomain',                default='') }}"
    _traefik_custom_labels:            "{{ lookup('vars', _prefix ~ '_traefik_custom_labels',            default='') }}"
    _traefik_router_service:           "{{ lookup('vars', _prefix ~ '_traefik_router_service',           default=false) }}"
    _traefik_loadbalancer_server_port: "{{ lookup('vars', _prefix ~ '_traefik_loadbalancer_server_port', default=false) }}"
    _traefik_entrypoints:              "{{ lookup('vars', _prefix ~ '_traefik_entrypoints',              default='https') }}"
    _traefik_middlewares:              "{{ lookup('vars', _prefix ~ '_traefik_middlewares',              default=[]) }}"

  block:

    - name: "Setup traefik custom domain ({{ _prefix ~ '_traefik_domain' }})"
      ansible.builtin.set_fact:
        traefik_domain_label_value: "traefik.http.routers.{{ project_name }}.rule: Host(`{{ _traefik_domain }}`)"
        traefik_domains: "{{ [_traefik_domain] }}"
      when:
        - _traefik_domain

    - name: "Setup traefik custom subdomain ({{ _prefix ~ '_traefik_subdomain' }})"
      vars:
        _local_domain: "{{ _traefik_subdomain ~ '.' ~ local_base_domain }}"
        _exposed_domain: "{{ (exposed_base_domain | default(false)) | ternary(
          _traefik_subdomain ~ '.' ~ exposed_base_domain | default(''),
          false
        ) }}"
      ansible.builtin.set_fact:
        traefik_subdomain_label_value: "{{ traefik_subdomain_label }}: {{ _traefik_subdomain }}"
      when:
        - not traefik_domains is defined or not traefik_domains
        - traefik_subdomain_label is defined
        - _traefik_subdomain

    - name: Setup traefik default domains
      vars:
        _subdomain: "{{ _traefik_subdomain | default(project_name, true) }}"
        _local_domain: "{{ _subdomain ~ '.' ~ local_base_domain }}"
        _exposed_domain: "{{ (exposed_base_domain | default(false)) | ternary(
          _subdomain ~ '.' ~ exposed_base_domain | default(''),
          false
        ) }}"
      ansible.builtin.set_fact:
        traefik_domains: "{{ [_exposed_domain, _local_domain] | reject('eq', false) }}"
      when: not traefik_domains is defined or not traefik_domains


    - name: Setup traefik base labels
      vars:
        _traefik_project_base_host_rules: "(Host(`{{ traefik_domains | join('`) || Host(`') }}`))"
        _allowed_origins: "{{
          (traefik_domains | map('regex_replace', '^(.*)$', 'https://\\1'))
          + (access_control_allow_origin_dashboards | default([]))
        }}"
        _traefik_project_base_labels: |-
          #jinja2: trim_blocks: True, lstrip_blocks: True
          traefik.enable: {{  _traefik_enable | ternary('true', 'false') }}
          {{ traefik_domain_label_value    | default('') }}
          {{ traefik_subdomain_label_value | default('') }}

          {% if _traefik_custom_labels %}
          {{ _traefik_custom_labels }}
          {% endif %}

          {% if _traefik_loadbalancer_server_port %}
          traefik.http.services.{{ project_name }}.loadbalancer.server.port: {{ _traefik_loadbalancer_server_port }}
          {% endif %}
          {% if _traefik_router_service %}
          traefik.http.routers.{{ project_name }}.service: {{ _traefik_router_service }}
          {% endif %}
          traefik.http.routers.{{ project_name }}.entrypoints: {{ _traefik_entrypoints }}

          {% if _traefik_middlewares | length > 0 %}
          traefik.http.routers.{{ project_name }}.middlewares: >-
            {{ _traefik_middlewares | join(', ') }}
          {% endif %}

          {% if project_name ~ '-cors@docker' in _traefik_middlewares %}
          traefik.http.middlewares.{{ project_name }}-cors.headers.accessControlMaxAge: {{ project_access_control_max_age | default(100) }}
          traefik.http.middlewares.{{ project_name }}-cors.headers.addVaryHeader: true
          traefik.http.middlewares.{{ project_name }}-cors.headers.accessControlAllowMethods: "{{ project_access_control_allow_methods | default('*') }}"
          traefik.http.middlewares.{{ project_name }}-cors.headers.accessControlAllowHeaders: "{{ project_access_control_allow_headers | default('*') }}"
          traefik.http.middlewares.{{ project_name }}-cors.headers.accesscontrolalloworiginlist: >-
            {{ _allowed_origins | join(', ') }}
          {% endif %}
      ansible.builtin.set_fact:
        traefik_project_base_host_rules: "{{ _traefik_project_base_host_rules }}"
        traefik_project_base_labels:     "{{ _traefik_project_base_labels | regex_replace('\n\n\n(\n)*', '\n\n', multiline=True) }}"


    - name: Setup project default network
      ansible.builtin.set_fact:
        traefik_project_default_network: |-
          #jinja2: trim_blocks: True, lstrip_blocks: True
          default:
            driver: bridge
            ipam:
              driver: default
              {% if (compose_ipv4_subnet | default(false)) or (compose_ipv6_subnet | default(false)) %}
              config:
                {% if compose_ipv4_subnet | default(false) %}
                - subnet: {{ compose_ipv4_subnet | default('') }}
                {% endif %}
                {% if compose_ipv6_subnet | default(false) %}
                - subnet: {{ compose_ipv6_subnet | default('') }}
                {% endif %}
              {% endif %}
            {% if compose_ipv6_subnet | default(false) %}
            enable_ipv6: true
            {% endif %}


#    - name: Debug
#      ansible.builtin.debug:
#        msg:
#          - "project_name:                      {{ project_name                      | default('???') }}"
#          - "_prefix:                           {{ _prefix                           | default('???') }}"
#          - ""
#          - "_traefik_enable:                   {{ _traefik_enable                   | default('???') }}"
#          - "_traefik_domain:                   {{ _traefik_domain                   | default('???') }}"
#          - "_traefik_subdomain:                {{ _traefik_subdomain                | default('???') }}"
#          - "_traefik_custom_labels:            {{ _traefik_custom_labels            | default('???') }}"
#          - "_traefik_router_service:           {{ _traefik_router_service           | default('???') }}"
#          - "_traefik_loadbalancer_server_port: {{ _traefik_loadbalancer_server_port | default('???') }}"
#          - "_traefik_entrypoints:              {{ _traefik_entrypoints              | default('???') }}"
#          - "_traefik_middlewares:              {{ _traefik_middlewares              | default('???') }}"
#          - ""
#          - "traefik_domain_label_value:    {{ traefik_domain_label_value }}"
#          - "traefik_subdomain_label_value: {{ traefik_subdomain_label_value }}"
#          - "traefik_domains:               {{ traefik_domains }}"
#          - "traefik_project_base_host_rules: {{ traefik_project_base_host_rules }}"
#          - ""
#          - "traefik_project_base_labels:"
#          - "{{ traefik_project_base_labels }}"
#          - ""
#          - "traefik_project_default_network:"
#          - "{{ traefik_project_default_network }}"
