---

## Check

- name: Check base variables
  ansible.builtin.assert:
    that:
      - docker_project_name is defined and docker_project_name
      - docker_projects_path is defined and docker_projects_path
  tags: ["init", "check"]

- name: "Check base directory is writeable: {{ docker_projects_path }}"
  ansible.builtin.stat: { path: "{{ docker_projects_path }}" }
  register: _dir
  failed_when: not _dir.stat.exists or not _dir.stat.writeable or not (_dir.stat.isdir or _dir.stat.islnk)
  tags: ["init", "check"]

## Init

- name: Init Traefik Docker Compose project vars
  ansible.builtin.include_tasks: _init-vars.yml
